// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutosubmitController from "./autosubmit_controller"
application.register("autosubmit", AutosubmitController)

import ActiveNavigationController from "./active_navigation_controller"
application.register("active-navigation", ActiveNavigationController)

import CountdownController from "./countdown_controller"
application.register("countdown", CountdownController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import DialogTriggerController from "./dialog_trigger_controller"
application.register("dialog-trigger", DialogTriggerController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import InfiniteScrollController from "./infinite_scroll_controller"
application.register("infinite-scroll", InfiniteScrollController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import ThemeController from "./theme_controller"
application.register("theme", ThemeController)

import NestedFormController from "./nested_form_controller"
application.register("nested-form", NestedFormController)

import NoiseManagerController from "./noise_manager_controller"
application.register("noise-manager", NoiseManagerController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)

import CookieConsentController from "./cookie_consent_controller"
application.register("cookie-consent", CookieConsentController)

import SidebarMenuController from "./sidebar_menu_controller"
application.register("sidebar-menu", SidebarMenuController)

import SidebarDrawerController from "./sidebar_drawer_controller"
application.register("sidebar-drawer", SidebarDrawerController)

import SkipLinkController from "./skip_link_controller"
application.register("skip-link", SkipLinkController)

import ChartController from "./chart_controller"
application.register("chart", ChartController)

import RightDrawerController from "./right_drawer_controller"
application.register("right-drawer", RightDrawerController)

import ProposalEditorController from "./proposal_editor_controller"
application.register("proposal-editor", ProposalEditorController)

import ReportContributeController from "./report_contribute_controller"
application.register("report-contribute", ReportContributeController)

import VoteRankingController from "./vote_ranking_controller"
application.register("vote-ranking", VoteRankingController)

import RevisionHistoryController from "./revision_history_controller"
application.register("revision-history", RevisionHistoryController)

import QuorumFormController from "./quorum_form_controller"
application.register("quorum-form", QuorumFormController)

import CalendarController from "./calendar_controller"
application.register("calendar", CalendarController)

import MapController from "./map_controller"
application.register("map", MapController)

import MunicipalitySelectController from "./municipality_select_controller"
application.register("municipality-select", MunicipalitySelectController)
