inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

Style/Documentation:
  Enabled: false

Layout/MultilineOperationIndentation:
    EnforcedStyle: indented

Style/NonNilCheck:
  IncludeSemanticChanges: true

Layout/DotPosition:
  EnforcedStyle: trailing

Style/FrozenStringLiteralComment:
  Enabled: false

Rails/ActiveRecordOverride:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false


Layout/LineLength:
  Exclude:
    - config/locales/plurals.rb

AllCops:
  NewCops: enable
  Exclude:
    - 'node_modules/**/*'
    - 'uploads/**/*'
    - 'bin/**/*'
    - 'script/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
