version: '3.8'

services:
  airesis:
    build: .
    command: bundle exec rails s -b 0.0.0.0 --pid /tmp/server.pid
    environment:
      - DATABASE_URL=postgresql://postgres@db
      - RAILS_ENV=development
      - NODE_OPTIONS=--openssl-legacy-provider
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - db
    ports:
      - "3000:3000"

  solid_queue:
    build: .
    command: bundle exec rails solid_queue:start
    environment:
      - DATABASE_URL=postgresql://postgres@db
      - RAILS_ENV=development
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules

  mailpit:
    image: axllent/mailpit
    ports:
      - "8025:8025"
      - "1025:1025"

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - airesisDB:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  airesisDB:
  node_modules:
